apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx4
  namespace: nginx-ingress4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx4
    spec:
      containers:
      - image: gcr.io/google_containers/nginx-ingress-controller:0.8.3
        name: nginx4
        imagePullPolicy: Always
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - /nginx-ingress-controller
        - --default-backend-service=nginx-ingress4/default-http-backend
        - --nginx-configmap=nginx-ingress4/nginx4
